import { Product, Category } from './types';

export const CATEGORIES: Category[] = [
  {
    id: '1',
    name: 'Spices',
    slug: 'spices',
    description: 'Premium Indian spices and powders, from whole chillies to artisanal blends.',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '2',
    name: 'Dry Fruits',
    slug: 'dry-fruits',
    description: 'Premium quality nuts and dried fruits sourced from the best origins.',
    image: 'https://images.unsplash.com/photo-1596591606975-97ee5cef3a1e?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '3',
    name: 'Teas',
    slug: 'teas',
    description: 'Exquisite black, green, and white teas from India\'s finest estates.',
    image: 'https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '4',
    name: 'Herbal Teas',
    slug: 'herbal-teas',
    description: 'Natural infusions and wellness teas for a healthy lifestyle.',
    image: 'https://images.unsplash.com/photo-1576092729250-a9c58e737a6b?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '5',
    name: 'Pulses & Lentils',
    slug: 'pulses-lentils',
    description: 'Nutritious Indian pulses and lentils for wholesale export.',
    image: 'https://images.unsplash.com/photo-1585993002159-29528973a12a?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '6',
    name: 'Other Products',
    slug: 'other-products',
    description: 'Premium Basmati rice, tamarind, jaggery, and more.',
    image: 'https://images.unsplash.com/photo-1586201327693-86629f7bb1f3?auto=format&fit=crop&q=80&w=800',
  },
];

export const PRODUCTS: Product[] = [
  // Spices
  {
    id: 's1',
    name: 'Teja Red Chilli',
    category: 'spices',
    description: 'Highly pungent red chilli variety with a fiery heat and vibrant red color.',
    pricePerKg: 18,
    minOrder: 100,
    origin: 'Guntur, India',
    image: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&q=90&w=1000',
    pungency: 'Extra Hot'
  },
  {
    id: 's2',
    name: 'Turmeric Finger',
    category: 'spices',
    description: 'Premium quality whole turmeric fingers with high curcumin content.',
    pricePerKg: 12,
    minOrder: 50,
    origin: 'Erode, India',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=90&w=1000',
  },
  {
    id: 's3',
    name: 'Green Cardamom (Elaichi)',
    category: 'spices',
    description: 'Extra large green cardamom pods with intense aroma and flavor.',
    pricePerKg: 42,
    minOrder: 10,
    origin: 'Kerala, India',
    image: 'https://finebuy.co.in/wp-content/uploads/2022/07/Green-Cardamom.webp',
    featured: true,
    grade: 'Extra Bold'
  },
  {
    id: 's4',
    name: 'Black Pepper',
    category: 'spices',
    description: 'Bold black peppercorns with a sharp, spicy flavor and woody aroma.',
    pricePerKg: 15,
    minOrder: 25,
    origin: 'Malabar, India',
    image: 'https://images.unsplash.com/photo-1532336414038-cf19250c5757?auto=format&fit=crop&q=90&w=1000',
  },
  {
    id: 's5',
    name: 'Garam Masala',
    category: 'spices',
    description: 'Traditional blend of ground spices for authentic Indian flavor.',
    pricePerKg: 22,
    minOrder: 20,
    origin: 'Mumbai, India',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=90&w=1000',
  },

  // Teas
  {
    id: 't1',
    name: 'Assam CTC Black Tea',
    category: 'teas',
    description: 'Strong, full-bodied black tea with a malty flavor, perfect for milk tea.',
    pricePerKg: 14,
    minOrder: 50,
    origin: 'Assam, India',
    image: 'https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?auto=format&fit=crop&q=90&w=1000',
    grade: 'CTC'
  },
  {
    id: 't2',
    name: 'Darjeeling Black Tea',
    category: 'teas',
    description: 'The "Champagne of Teas" with a delicate, floral, and muscatel flavor.',
    pricePerKg: 65,
    minOrder: 10,
    origin: 'Darjeeling, India',
    image: 'https://images.unsplash.com/photo-1563911302283-d2bc129e7570?auto=format&fit=crop&q=90&w=1000',
    featured: true,
  },
  {
    id: 't3',
    name: 'Premium Green Tea',
    category: 'teas',
    description: 'Fresh and light green tea leaves rich in antioxidants.',
    pricePerKg: 35,
    minOrder: 20,
    origin: 'Nilgiri, India',
    image: 'https://images.unsplash.com/photo-1582722872445-44c567c318d7?auto=format&fit=crop&q=90&w=1000',
  },

  // Herbal Teas
  {
    id: 'ht1',
    name: 'Tulsi (Holy Basil) Tea',
    category: 'herbal-teas',
    description: 'Sacred herb infusion known for its stress-relieving and healing properties.',
    pricePerKg: 28,
    minOrder: 15,
    origin: 'India',
    image: 'https://images.unsplash.com/photo-1626125336173-982462303732?auto=format&fit=crop&q=90&w=1000',
  },
  {
    id: 'ht2',
    name: 'Chamomile Tea',
    category: 'herbal-teas',
    description: 'Whole chamomile flowers for a calming and soothing herbal infusion.',
    pricePerKg: 32,
    minOrder: 10,
    origin: 'India',
    image: 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&q=90&w=1000',
  },

  // Dry Fruits
  {
    id: 'df1',
    name: 'Cashew Nuts (W240)',
    category: 'dry-fruits',
    description: 'Premium whole white cashew nuts, large size and buttery texture.',
    pricePerKg: 16,
    minOrder: 25,
    origin: 'Konkan, India',
    image: 'https://images.unsplash.com/photo-1590502593747-42a996133562?auto=format&fit=crop&q=90&w=1000',
    featured: true,
    grade: 'W240'
  },
  {
    id: 'df2',
    name: 'Premium Almonds',
    category: 'dry-fruits',
    description: 'Sweet, crunchy almonds sourced from the finest orchards.',
    pricePerKg: 14,
    minOrder: 25,
    origin: 'California/India',
    image: 'https://images.unsplash.com/photo-1508029060042-5819df148ac9?auto=format&fit=crop&q=90&w=1000',
  },
  {
    id: 'df3',
    name: 'Pistachios',
    category: 'dry-fruits',
    description: 'Naturally opened, roasted and salted premium pistachios.',
    pricePerKg: 24,
    minOrder: 20,
    origin: 'Iran/India',
    image: 'https://images.unsplash.com/photo-1527324688151-0e627063f2b1?auto=format&fit=crop&q=90&w=1000',
  },

  // Pulses
  {
    id: 'p1',
    name: 'Kabuli Chickpeas',
    category: 'pulses-lentils',
    description: 'Large, creamy white chickpeas perfect for hummus and curries.',
    pricePerKg: 8,
    minOrder: 100,
    origin: 'Maharashtra, India',
    image: 'https://images.unsplash.com/photo-1585993002159-29528973a12a?auto=format&fit=crop&q=90&w=1000',
  },
  {
    id: 'p2',
    name: 'Red Lentils (Masoor Dal)',
    category: 'pulses-lentils',
    description: 'Split red lentils that cook quickly and are highly nutritious.',
    pricePerKg: 6,
    minOrder: 100,
    origin: 'Madhya Pradesh, India',
    image: 'https://images.unsplash.com/photo-1515942400420-2b98fed1f515?auto=format&fit=crop&q=90&w=1000',
  },

  // Other
  {
    id: 'o1',
    name: 'Basmati Rice (Long Grain)',
    category: 'other-products',
    description: 'Extra long grain aromatic basmati rice, aged for superior flavor.',
    pricePerKg: 10,
    minOrder: 500,
    origin: 'Punjab, India',
    image: 'https://images.unsplash.com/photo-1586201327693-86629f7bb1f3?auto=format&fit=crop&q=90&w=1000',
    featured: true,
  },
  {
    id: 'o2',
    name: 'Tamarind (Slab)',
    category: 'other-products',
    description: 'Seedless tamarind slabs with a perfect balance of sweet and sour.',
    pricePerKg: 5,
    minOrder: 50,
    origin: 'South India',
    image: 'https://images.unsplash.com/photo-1593001874117-c99c800e3eb7?auto=format&fit=crop&q=90&w=1000',
  },
  {
    id: 'o3',
    name: 'Jaggery (Block)',
    category: 'other-products',
    description: 'Natural unrefined cane sugar blocks with a rich, caramel-like taste.',
    pricePerKg: 4,
    minOrder: 50,
    origin: 'Kolhapur, India',
    image: 'https://images.unsplash.com/photo-1608327133347-2485043d3b74?auto=format&fit=crop&q=90&w=1000',
  },
];
